create table if not exists public.growth_events (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  event_name text not null,
  event_source text not null default 'app',
  plan text null,
  properties jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint growth_events_event_name_check check (
    event_name in (
      'diagnostic_started',
      'diagnostic_completed',
      'lesson_started',
      'trial_started',
      'trial_exhausted',
      'upgrade_clicked',
      'checkout_started',
      'subscription_activated',
      'subscription_cancelled',
      'payment_failed'
    )
  ),
  constraint growth_events_event_source_check check (
    event_source in ('app', 'stripe', 'system')
  ),
  constraint growth_events_plan_check check (
    plan is null or plan in ('student', 'family')
  ),
  constraint growth_events_properties_object_check check (
    jsonb_typeof(properties) = 'object'
  )
);

create index if not exists growth_events_event_name_occurred_at_idx
  on public.growth_events (event_name, occurred_at desc);

create index if not exists growth_events_user_id_occurred_at_idx
  on public.growth_events (user_id, occurred_at desc)
  where user_id is not null;

alter table public.growth_events enable row level security;

-- Growth analytics are server-owned. Browser roles should not reach this table
-- directly; the app's authenticated API derives user_id from the verified token.
revoke all on table public.growth_events from anon, authenticated;
revoke all on sequence public.growth_events_id_seq from anon, authenticated;

grant select, insert on table public.growth_events to service_role;
grant usage, select on sequence public.growth_events_id_seq to service_role;
