create table if not exists public.class_enrollments (
  id bigint generated by default as identity primary key,
  classroom_id uuid not null references public.teacher_classrooms(id) on delete cascade,
  student_user_id uuid not null references auth.users(id) on delete cascade,
  student_display_name text not null check (char_length(btrim(student_display_name)) between 1 and 120),
  joined_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint class_enrollments_classroom_student_unique unique (classroom_id, student_user_id)
);

create table if not exists public.assignment_completions (
  id bigint generated by default as identity primary key,
  assignment_id uuid not null references public.teacher_assignments(id) on delete cascade,
  classroom_id uuid not null references public.teacher_classrooms(id) on delete cascade,
  student_user_id uuid not null references auth.users(id) on delete cascade,
  lesson_completion_id bigint not null references public.lesson_completions(id) on delete cascade,
  module_id text not null,
  mastery_label text not null check (mastery_label in ('Mastered', 'Developing', 'Intervention Needed')),
  mastery_score integer not null check (mastery_score between 0 and 100),
  completed_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now(),
  constraint assignment_completions_assignment_lesson_unique unique (assignment_id, lesson_completion_id)
);

create index if not exists class_enrollments_student_idx on public.class_enrollments (student_user_id, joined_at desc);
create index if not exists class_enrollments_classroom_idx on public.class_enrollments (classroom_id, joined_at desc);
create index if not exists assignment_completions_classroom_student_idx on public.assignment_completions (classroom_id, student_user_id, completed_at desc);
create index if not exists assignment_completions_assignment_idx on public.assignment_completions (assignment_id, completed_at desc);
create index if not exists assignment_completions_lesson_idx on public.assignment_completions (lesson_completion_id);

alter table public.class_enrollments enable row level security;
alter table public.assignment_completions enable row level security;
revoke all on table public.class_enrollments from anon, authenticated;
revoke all on table public.assignment_completions from anon, authenticated;
grant select on table public.class_enrollments to authenticated;
grant select on table public.assignment_completions to authenticated;
grant select, insert, update, delete on table public.class_enrollments to service_role;
grant select, insert, update, delete on table public.assignment_completions to service_role;
revoke all on sequence public.class_enrollments_id_seq from anon, authenticated;
revoke all on sequence public.assignment_completions_id_seq from anon, authenticated;
grant usage, select on sequence public.class_enrollments_id_seq to service_role;
grant usage, select on sequence public.assignment_completions_id_seq to service_role;

create policy "Students can view their own class enrollments" on public.class_enrollments for select to authenticated using ((select auth.uid()) = student_user_id);
create policy "Students can view their own assignment results" on public.assignment_completions for select to authenticated using ((select auth.uid()) = student_user_id);
