create table if not exists public.skill_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_completion_id uuid not null,
  skill_code text not null check (skill_code ~ '^A\\.[0-9]{1,2}[A-Z]$'),
  completed_at timestamp with time zone not null,
  mastery_label text not null check (
    mastery_label in ('Mastered', 'Developing', 'Intervention Needed')
  ),
  mastery_score integer not null check (mastery_score between 0 and 100),
  time_on_skill_seconds integer not null default 0
    check (time_on_skill_seconds between 0 and 604800),
  item_records jsonb not null default '[]'::jsonb,
  qa_mode boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint skill_attempts_user_completion_unique unique (
    user_id,
    client_completion_id
  )
);

create index if not exists skill_attempts_user_skill_completed_idx
  on public.skill_attempts (user_id, skill_code, completed_at desc);

create table if not exists public.skill_mastery (
  user_id uuid not null references auth.users(id) on delete cascade,
  skill_code text not null check (skill_code ~ '^A\\.[0-9]{1,2}[A-Z]$'),
  attempts_count integer not null default 0 check (attempts_count >= 0),
  latest_score integer not null default 0 check (latest_score between 0 and 100),
  best_score integer not null default 0 check (best_score between 0 and 100),
  mastery_label text not null default 'Intervention Needed' check (
    mastery_label in ('Mastered', 'Developing', 'Intervention Needed')
  ),
  total_time_on_skill_seconds integer not null default 0
    check (total_time_on_skill_seconds >= 0),
  misconception_counts jsonb not null default '{}'::jsonb,
  last_practiced_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  primary key (user_id, skill_code)
);

create index if not exists skill_mastery_user_updated_idx
  on public.skill_mastery (user_id, updated_at desc);

alter table public.skill_attempts enable row level security;
alter table public.skill_mastery enable row level security;

revoke all on table public.skill_attempts from anon, authenticated;
revoke all on table public.skill_mastery from anon, authenticated;
grant select, insert, update on table public.skill_attempts to service_role;
grant select, insert, update on table public.skill_mastery to service_role;

revoke all on sequence public.skill_attempts_id_seq from anon, authenticated;
grant usage, select on sequence public.skill_attempts_id_seq to service_role;

comment on table public.skill_attempts is
  'Idempotent authenticated skill-attempt history maintained by the Tolux server.';
comment on table public.skill_mastery is
  'Per-student skill mastery aggregate maintained by the Tolux server.';
