create table if not exists public.lesson_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_completion_id uuid not null,
  module_id text not null,
  completed_at timestamp with time zone not null,
  mastery_label text not null,
  mastery_score integer not null check (mastery_score between 0 and 100),
  is_subscriber boolean not null default false,
  qa_mode boolean not null default false,
  time_on_skill_seconds integer not null default 0
    check (time_on_skill_seconds between 0 and 604800),
  item_records jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint lesson_completions_mastery_label_check check (
    mastery_label in ('Mastered', 'Developing', 'Intervention Needed')
  ),
  constraint lesson_completions_user_client_unique unique (
    user_id,
    client_completion_id
  )
);

create index if not exists lesson_completions_user_completed_idx
  on public.lesson_completions (user_id, completed_at desc);

create index if not exists lesson_completions_user_module_idx
  on public.lesson_completions (user_id, module_id, completed_at desc);

alter table public.lesson_completions enable row level security;

revoke all on table public.lesson_completions from anon, authenticated;
grant select, insert, update on table public.lesson_completions to service_role;

revoke all on sequence public.lesson_completions_id_seq from anon, authenticated;
grant usage, select on sequence public.lesson_completions_id_seq to service_role;

comment on table public.lesson_completions is
  'Authenticated lesson-completion and mastery history. Accessed only by the Tolux server service role.';
